a=input('Digite algo:')
print(type(a))
print('tem numero -',a.isnumeric())
print('tem alfabeto -',a.isalpha())
print('tem alfanumerico -',a.isalnum())
print('tem espaso -',a.isspace())
print('esta maiuscola -',a.isupper())
print('esta minuscola -',a.islower())
print('capitalizada -',a.istitle())